name: QA Automation Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Override upload-artifact to v4
        uses: actions/upload-artifact@v4
        with:
          name: noop
          path: README.md
          retention-days: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Start JSON Server
        run: npx json-server --watch db.json --port 3000 &


      - name: Run Playwright tests (E2E + API)
        run: npx playwright test --reporter=line,html --output=reports/playwright

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: reports/playwright

  k6-load-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup k6
        uses: grafana/setup-k6-action@v1
        with:
          k6-version: v0.52.0

      - name: Run K6 Load Test
        run: k6 run --out json=reports/k6/results.json tests/performance/load-test.js

      - name: Upload K6 Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: reports/k6

